//quesion 1

var username;
var myName= "Hamza Iqbal";
var message = "Hellow world";

alert(message);
console.log(message);


//question no 2
 
var fullname= "Hamza iqbal";
var age = 20;
var field = "Certified Wev-developer";

window.alert(

    "Name" + fullname + "\n" +
    "Age"  + age + "\n" + 
    "feild" + field + "\n"
);

//question no 3
var message = "PIZZA\nPIZZ\nPIZ\nPI\nP";

alert(message);

//question no 4
var email = "My email address is Hamzaiqbal123@gmail.com"
alert(email)
console.log(email)

//question no 5
var book = "I am trying to learn from the Book A smater way to learn java script"
alert(book)
console.log(book)

//question no 6

var random= "▬▬▬▬▬▬▬▬▬۩۞۩▬▬▬▬▬▬▬▬▬"
alert(random)
console.log(random)

//QUESTION NO 7


const container =document.getElementById("demo")
container.innerHTML = "Hey there, this sentence is written from JavaScript to HTML."


console.log(container)